services:
  db:
    image: postgres:15
    container_name: job_market_db
    env_file: .env
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PW_DB}
      POSTGRES_DB: ${TABLE_DB}
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - job_data_network
    
  metabase:
    image: metabase/metabase:latest
    container_name: job_market_bi
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    networks:
      - job_data_network

  dashboard_server:
    image: nginx:alpine
    container_name: job_market_web
    user: root
    ports:
      - "8000:80"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/airflow/dags:/usr/share/nginx/html:ro
    restart: always
    networks:
      - job_data_network
  
volumes:                  
  postgres_data_vol:
networks:
  job_data_network:
    name: job_data_network
    driver: bridge
    